services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - ../:/app
      - ./certs:/certs
    working_dir: /app
    env_file:
      - ../.env
    environment:
      - PYTHONPATH=/app/src
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    command: >
      uvicorn src.api.main:app
      --host 0.0.0.0
      --port 8000
      --ssl-keyfile /certs/dev.key
      --ssl-certfile /certs/dev.crt
    networks:
      - quant-bridge

  postgres:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - quant-bridge

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - quant-bridge

networks:
  quant-bridge:
    external: true
