"""Add audit_log table

Revision ID: 811626fefbd5
Revises: a80d736ff8c0
Create Date: 2025-07-27 09:53:12.107343

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "811626fefbd5"
down_revision: Union[str, Sequence[str], None] = "a80d736ff8c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("strategy_id", sa.UUID(), nullable=True),
        sa.Column(
            "decision_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("llm_rationale", sa.Text(), nullable=True),
        sa.Column(
            "risk_assessment", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "system_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit_log")
    # ### end Alembic commands ###
